import type { ActivityItem, GardenPost } from "./types";

export const starterPosts: GardenPost[] = [
  {
    id: "post-1",
    title: "A quiet system for capturing ideas",
    description:
      "The small habits and gentle constraints that keep my digital garden alive.",
    content:
      "## A garden needs a path\n\nI used to wait for an idea to feel complete before writing it down. Most of them disappeared. Now I keep a small system: capture quickly, connect generously, and return when the thought has had time to grow.\n\n> The goal is not to publish more. It is to notice more.\n\n### The three-part rhythm\n\n- **Collect** fragments without judging them\n- **Tend** the notes that keep calling me back\n- **Share** only when the idea can help someone else\n\nThis garden is less an archive and more a conversation with my past self.",
    status: "Published",
    type: "Content",
    category: "Notes",
    tags: ["notes", "systems", "practice"],
    slug: "quiet-system-for-capturing-ideas",
    coverImage: "",
    seoTitle: "A quiet system for capturing ideas",
    seoDescription:
      "A personal system for collecting, tending, and sharing ideas in a digital garden.",
    updatedAt: "2026-08-03T14:24:00.000Z",
    publishedAt: "2026-08-03T14:24:00.000Z",
    likes: 48,
    bookmarks: 19,
    comments: 6,
    versions: [
      { id: "v-1-3", label: "Published version", date: "Aug 3, 2026 · 5:54 PM" },
      { id: "v-1-2", label: "Edited structure", date: "Aug 2, 2026 · 10:12 AM" },
      { id: "v-1-1", label: "First draft", date: "Jul 31, 2026 · 8:40 PM" },
    ],
  },
  {
    id: "post-2",
    title: "Field notes from a week without feeds",
    description:
      "What changed when I replaced algorithmic timelines with walks, books, and calls.",
    content:
      "## Seven days at a slower frequency\n\nThe first day felt unusually quiet. By the fourth, the quiet had become spacious.\n\nI noticed that boredom is not an empty state—it is an invitation. Without the reflex to refresh, I started finishing thoughts again.",
    status: "Draft",
    type: "Content",
    category: "Life",
    tags: ["attention", "offline"],
    slug: "a-week-without-feeds",
    coverImage: "",
    seoTitle: "Field notes from a week without feeds",
    seoDescription: "Observations from taking a deliberate week away from social feeds.",
    updatedAt: "2026-08-02T08:10:00.000Z",
    publishedAt: "",
    likes: 0,
    bookmarks: 0,
    comments: 0,
    versions: [
      { id: "v-2-2", label: "Autosaved draft", date: "Aug 2, 2026 · 11:40 AM" },
      { id: "v-2-1", label: "First draft", date: "Aug 1, 2026 · 7:15 PM" },
    ],
  },
  {
    id: "post-3",
    title: "Little weather station",
    description:
      "A weekend build that turns local weather into a quiet object for the desk.",
    content:
      "## Making data feel tangible\n\nA small e-ink display, a temperature sensor, and a maple frame. The station updates slowly by design—weather as ambience rather than another alert.",
    status: "Published",
    type: "Content",
    category: "Build",
    tags: ["hardware", "weather", "weekend"],
    slug: "little-weather-station",
    coverImage: "",
    seoTitle: "Little weather station — a weekend build",
    seoDescription: "Building a calm, desk-sized weather station with an e-ink display.",
    updatedAt: "2026-07-28T17:35:00.000Z",
    publishedAt: "2026-07-28T17:35:00.000Z",
    likes: 71,
    bookmarks: 34,
    comments: 9,
    versions: [
      { id: "v-3-2", label: "Published version", date: "Jul 28, 2026 · 9:05 PM" },
      { id: "v-3-1", label: "First draft", date: "Jul 26, 2026 · 4:30 PM" },
    ],
  },
  {
    id: "post-4",
    title: "Books I return to when starting again",
    description:
      "A small shelf for creative resets, patient work, and remembering what matters.",
    content:
      "## The restart shelf\n\nSome books are less like things you finish and more like places you visit. These are the ones I reach for when the work feels too complicated.",
    status: "Scheduled",
    type: "Content",
    category: "Shelf",
    tags: ["books", "creativity"],
    slug: "books-for-starting-again",
    coverImage: "",
    seoTitle: "Books I return to when starting again",
    seoDescription: "A reading list for creative resets and patient work.",
    updatedAt: "2026-07-26T10:00:00.000Z",
    publishedAt: "2026-08-08T06:30:00.000Z",
    likes: 0,
    bookmarks: 0,
    comments: 0,
    versions: [{ id: "v-4-1", label: "Scheduled version", date: "Jul 26, 2026 · 1:30 PM" }],
  },
  {
    id: "post-5",
    title: "On keeping a commonplace book",
    description: "Notes on collecting sentences, questions, and useful friction.",
    content:
      "## A book of echoes\n\nThe commonplace book is where other people's sentences meet my own unfinished questions.",
    status: "Published",
    type: "Content",
    category: "Notes",
    tags: ["books", "notes"],
    slug: "keeping-a-commonplace-book",
    coverImage: "",
    seoTitle: "On keeping a commonplace book",
    seoDescription: "A short note on the useful practice of keeping a commonplace book.",
    updatedAt: "2026-07-20T12:40:00.000Z",
    publishedAt: "2026-07-20T12:40:00.000Z",
    likes: 36,
    bookmarks: 25,
    comments: 4,
    versions: [{ id: "v-5-1", label: "Published version", date: "Jul 20, 2026 · 4:10 PM" }],
  },
];

export const starterActivity: ActivityItem[] = [
  {
    id: "activity-1",
    action: "Published",
    detail: "A quiet system for capturing ideas",
    time: "2 hours ago",
    kind: "publish",
  },
  {
    id: "activity-2",
    action: "New comment",
    detail: "Mina replied to Little weather station",
    time: "5 hours ago",
    kind: "comment",
  },
  {
    id: "activity-3",
    action: "Draft updated",
    detail: "Field notes from a week without feeds",
    time: "Yesterday",
    kind: "edit",
  },
  {
    id: "activity-4",
    action: "New subscriber",
    detail: "Your garden now has 284 readers",
    time: "Yesterday",
    kind: "subscriber",
  },
];
